### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [Bonn93/jira-container-deploys#1]
Hi,<br><br>url : https://github.com/Bonn93/jira-container-deploys/blob/496038a28272147a921f4e04e9e396a93ae80844/ansible-ec2/jira01.yml <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by Bonn93** [comment]
This repo is for demos
